import turtle
a = input('please input True/False: ')
a = bool(a=='True')

turtle.shape('turtle')
turtle.pensize(5)
turtle.penup()
turtle.goto(-30, -15)
turtle.pendown()
turtle.fillcolor('green')
turtle.begin_fill()
turtle.left(90)
turtle.forward(30)
turtle.right(90)
turtle.forward(60)
turtle.right(90)
turtle.forward(30)
turtle.right(90)
turtle.forward(60)
turtle.end_fill()
turtle.penup()
turtle.goto(0, 0)
turtle.setheading(0)
turtle.forward(30)
turtle.pendown()
turtle.forward(100)
turtle.left(90)
turtle.forward(150)
turtle.left(90)
turtle.forward(260)
turtle.left(90)
turtle.forward(150)
turtle.left(90)
turtle.forward(100)
turtle.penup()
turtle.goto(0, 150)
turtle.pendown()

if True != a:
 turtle.fillcolor('black')
 turtle.begin_fill()
 turtle.circle(50)
 turtle.end_fill()
 turtle.done()
else:
 turtle.pencolor('yellow')
 turtle.fillcolor('Yellow')
 turtle.begin_fill()
 turtle.circle(50)
 turtle.end_fill()
 turtle.done()
